info:
  name: CartaPorte-ConfigAutotransporte
  type: http
  seq: 6

http:
  method: GET
  url: "{{SERVER}}/api/catalogs/cartaporte/ConfigAutotransporte"
  headers:
    - name: User-Agent
      value: "{{UserName}}"
  body:
    type: json
    data: ""
  auth:
    type: basic
    username: "{{UserName}}"
    password: "{{Password}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
